import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleDashed, Database, GitBranch, MapPinned, Quote, Search, Users } from "lucide-react";
import { events, people, sources, verifiedEvents, years } from "@/data/rewind";

export default function Home(){
  const provisional=events.length-verifiedEvents.length;
  const featured=people.map(person=>({person,count:events.filter(event=>event.participants.some(participant=>participant.personId===person.id)).length,places:new Set(events.filter(event=>event.participants.some(participant=>participant.personId===person.id)).map(event=>event.city)).size})).filter(item=>item.count).sort((a,b)=>b.count-a.count).slice(0,6);
  return <>
    <section className="hub-hero"><div className="hub-hero-copy"><span className="signal"><i/>TIME-INDEXED EVIDENCE</span><h1>History is not a page.<br/><em>It is a position in time.</em></h1><p>Explore documented lives through synchronized events, places, people and primary sources. Choose a person, move the timeline and watch the evidence change around them.</p><div className="hub-actions"><Link href="/people"><Users/>Choose a person <ArrowRight/></Link><Link href="/events"><Search/>Search every event</Link></div></div><aside className="hub-index-card"><div><small>ATLAS STATUS</small><span>LIVE INDEX</span></div><dl><div><dt>Events</dt><dd>{events.length}</dd></div><div><dt>People</dt><dd>{people.length}</dd></div><div><dt>Sources</dt><dd>{sources.length}</dd></div><div><dt>Places</dt><dd>{new Set(events.map(event=>event.city)).size}</dd></div></dl><p><CheckCircle2/>{verifiedEvents.length} verified records <span>·</span> <CircleDashed/>{provisional} provisional</p></aside><div className="hub-timeband" aria-hidden="true"><span>{years[0]}</span><i/><i/><i className="active"/><i/><i/><span>{years.at(-1)}</span></div></section>
    <section className="hub-launchpad"><div className="section-heading"><div><span className="eyebrow">CHOOSE A WAY IN</span><h2>Explore the atlas</h2></div><p>Every view is generated from the same event records, so time, place, people and evidence always remain connected.</p></div><div className="hub-launch-grid"><Link href="/people"><Users/><span><small>DOCUMENTED LIVES</small><b>People</b><p>Open a person and rewind their chronology.</p></span><ArrowRight/></Link><Link href="/events"><Database/><span><small>{events.length} RECORDS</small><b>Events</b><p>Search the central unit of the database.</p></span><ArrowRight/></Link><Link href="/places"><MapPinned/><span><small>GEOGRAPHY</small><b>Places</b><p>See where the evidence puts people over time.</p></span><ArrowRight/></Link><Link href="/relationships"><GitBranch/><span><small>INTERSECTIONS</small><b>Relationships</b><p>Trace every dated meeting between two lives.</p></span><ArrowRight/></Link><Link href="/quotes"><Quote/><span><small>WORDS IN CONTEXT</small><b>Quotes</b><p>Find statements attached to speakers and sources.</p></span><ArrowRight/></Link><Link href="/sources"><Database/><span><small>{sources.length} REFERENCES</small><b>Sources</b><p>Inspect the evidence behind each claim.</p></span><ArrowRight/></Link></div></section>
    <section className="hub-subjects"><div className="section-heading"><div><span className="eyebrow">PEOPLE IN THIS EDITION</span><h2>Start with a documented life</h2></div><Link href="/people">View everyone <ArrowRight/></Link></div><div className="hub-subject-grid">{featured.map(({person,count,places})=><Link href={`/person/${person.slug}`} key={person.id}><span className="person-monogram">{person.name.split(" ").map(name=>name[0]).slice(0,2).join("")}</span><div><small>{count} EVENT{count===1?"":"S"} · {places} PLACE{places===1?"":"S"}</small><b>{person.name}</b><p>{person.description}</p></div><ArrowRight/></Link>)}</div><div className="trust-strip"><span><CheckCircle2/>Confirmed means direct or authoritative evidence</span><span><CircleDashed/>Uncertainty remains visible, never silently interpolated</span><Link href="/methodology">Read the evidence standard <ArrowRight/></Link></div></section>
  </>;
}
